In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Display all columns
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\OnlineRetail.csv", encoding='latin1')

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [7]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [8]:
df.shape

(541909, 8)

In [9]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [10]:
df.select_dtypes(include=['int64','float64']).columns

Index(['Quantity', 'UnitPrice', 'CustomerID'], dtype='str')

In [11]:
df.select_dtypes(include='str').columns

Index(['InvoiceNo', 'StockCode', 'Description', 'InvoiceDate', 'Country'], dtype='str')

In [12]:
print("Total rows:", len(df))
print("Unique Invoice Numbers:", df["InvoiceNo"].nunique())

Total rows: 541909
Unique Invoice Numbers: 25900

In [13]:
print("Unique Stock Codes:", df["StockCode"].nunique())

Unique Stock Codes: 4070

In [14]:
print("Unique InvoiceNo + StockCode combinations:",
      df[["InvoiceNo", "StockCode"]].drop_duplicates().shape[0])

Unique InvoiceNo + StockCode combinations: 531225

In [15]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [16]:
# Percentage of missing values 
(df.isnull().sum()/len(df))*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [17]:
df.columns = df.columns.str.strip()
df["Description"] = df["Description"].str.strip()
df["Country"] = df["Country"].str.strip()

In [18]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [19]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [20]:
df.duplicated().sum()

np.int64(5268)

In [21]:
df = df.drop_duplicates()

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
# Missing Description
df["Description"] = df["Description"].fillna("Unknown Product")

In [24]:
# Missing CustomerID
df["CustomerID"] = df["CustomerID"].fillna(0)

In [25]:
# Convert CustomerID back to integer
df["CustomerID"] = df["CustomerID"].astype(int)

In [27]:
# Checking negative quantities and removing them
df[df["Quantity"] < 0]
(df["Quantity"] < 0).sum()

np.int64(10587)

In [28]:
df = df[df["Quantity"] > 0]

In [32]:
# Checking negative prices and removing them
df[df["UnitPrice"] < 0]
df = df[df["UnitPrice"] > 0]

In [33]:
# Canceled Orders
df[df["InvoiceNo"].astype(str).str.startswith("C")]
df["InvoiceNo"].astype(str).str.startswith("C").sum()
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

In [34]:
# Creating revenue column
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [35]:
df.to_csv("OnlineRetail_Cleaned.csv", index=False)

In [36]:
import os
print(os.getcwd())

C:\Users\Admin

In [37]:
df.to_csv(r"C:\Users\Admin\Documents\OnlineRetail_Cleaned.csv", index=False)